# SPDX-FileCopyrightText: 2023 Kevin de Jong <monkaii@hotmail.com>
# SPDX-License-Identifier: CC0-1.0

---

name: Conventional Commits
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write

jobs:
  commit-me:
    name: Conventional Commits Compliance
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run CommitMe
        uses: dev-build-deploy/commit-me@v0
        with:
          token: ${{ github.token }}
          include-commits: true
